export const homeObjOne = {
    id: 'about',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Premium Bank',
    headline: "Unlimited Transactions with zero fees",
    description: 'Get access to our exclusive app that allow you to send unlimited transactions without getting charged any fees',
    buttonLabel: 'Get started',
    imgStart: false,
    img: require('../../images/svg-4.svg'),
    alt: 'Car',
    dark: true,
    primary: true,
    darkText: false,
};


export const homeObjTwo = {
    id: 'home',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Unlimited Access',
    headline: "Unlimited Transactions with zero fees",
    description: 'Get access to our exclusive app that allow you to send unlimited transactions without getting charged any fees',
    buttonLabel: 'Get started',
    imgStart: true,
    img: require('../../images/svg-2.svg'),
    alt: 'PiggyBank',
    dark: false,
    primary: false,
    darkText: true,
};

export const homeObjThree = {
    id: 'discover',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Premium Bank',
    headline: "Unlimited Transactions with zero fees",
    description: 'Get access to our exclusive app that allow you to send unlimited transactions without getting charged any fees',
    buttonLabel: 'Get started',
    imgStart: false,
    img: require('../../images/svg-1.svg'),
    alt: 'Car',
    dark: false,
    primary: true,
    darkText: false,
};